name: Scraping Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: scraping
      run: | 
        cd tools
        yarn install
        node scraper.js
      env:
        KOUTOU_SYSTEM_USER_ID: ${{ secrets.KOUTOU_SYSTEM_USER_ID }}
        KOUTOU_SYSTEM_PASS: ${{ secrets.KOUTOU_SYSTEM_PASS }}
    - name: configure aws credentials
      if: success()
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: upload output to s3
      if: success()
      run: |
        FILE_NAME=$(grep -o '[0-9:.T-]*Z' ${{ github.workspace }}/tools/output.json).json
        aws s3 mv ${{ github.workspace }}/tools/output.json s3://trfv-scraping/koutou-lottery/$FILE_NAME
    - name: notify to slack
      if: always()
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: 'logs'
        slack-message: '{{ success() }}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      


