name: Scraping

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: | 
        cd tools
        npm install
        node scraper.js
      env:
        KOUTOU_SYSTEM_USER_ID: ${{ secrets.KOUTOU_SYSTEM_USER_ID }}
        KOUTOU_SYSTEM_PASS: ${{ secrets.KOUTOU_SYSTEM_PASS }}
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/tools/output.json
        if-no-files-found: error
